name: "tagged-release"

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.17.1

      - name: Check out code
        uses: actions/checkout@v1

      - name: Download modules
        run: go mod download

      - name: Build amd64 version for release
        run: go build -o postgresql_backup_linux_amd64

      - name: Build arm64 version for release
        run: GOARCH=arm64 go build -o postgresql_backup_linux_arm64

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            .env.example
            postgresql_backup_linux_amd64
            postgresql_backup_linux_arm64
      
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Development Build"
          files: |
            .env.example
            postgresql_backup_linux_amd64
            postgresql_backup_linux_arm64
